---
abstract: 'reversehttp for AnyEvent'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-ReverseHTTP
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Any::Moose: 0
  AnyEvent: 0
  AnyEvent::HTTP: 0
  Digest::SHA: 0
  Filter::Util::Call: 0
  HTTP::Request: 0
  Time::HiRes: 0
  URI::Escape: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/miyagawa/AnyEvent-ReverseHTTP.git
version: 0.04
